# Generated by Django 4.2.2 on 2026-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caraccident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("hour", models.IntegerField()),
                ("minute", models.IntegerField()),
                ("type", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("amountofdeath", models.IntegerField(db_column="AmountOfdeath")),
                ("amountofinjuries", models.IntegerField(db_column="AmountOfInjuries")),
                (
                    "sequenceofpartiesinvolved",
                    models.IntegerField(db_column="SequenceOfPartiesInvolved"),
                ),
                (
                    "vehicletype",
                    models.CharField(
                        blank=True, db_column="VehicleType", max_length=20, null=True
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(blank=True, db_column="Gender", null=True),
                ),
                ("age", models.IntegerField(blank=True, db_column="Age", null=True)),
                (
                    "levelofinjury",
                    models.IntegerField(
                        blank=True, db_column="LevelOfInjury", null=True
                    ),
                ),
                (
                    "weather",
                    models.IntegerField(blank=True, db_column="Weather", null=True),
                ),
                (
                    "speedlimit",
                    models.IntegerField(blank=True, db_column="SpeedLimit", null=True),
                ),
                (
                    "typeofroad",
                    models.IntegerField(blank=True, db_column="TypeOfroad", null=True),
                ),
                (
                    "locationofaccident",
                    models.IntegerField(
                        blank=True, db_column="LocationOfAccident", null=True
                    ),
                ),
            ],
            options={
                "db_table": "caraccident",
                "managed": True,
            },
        ),
    ]
